/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    FindUser: typeof import('./src/components/presence/FindUser.vue')['default']
    Help: typeof import('./src/components/presence/Help.vue')['default']
    IconFlagpackDe: typeof import('~icons/flagpack/de')['default']
    IconFlagpackUs: typeof import('~icons/flagpack/us')['default']
    IconMdiAlertBoxOutline: typeof import('~icons/mdi/alert-box-outline')['default']
    IconMdiAlertCircleOutline: typeof import('~icons/mdi/alert-circle-outline')['default']
    IconMdiCheck: typeof import('~icons/mdi/check')['default']
    IconMdiClipboardOutline: typeof import('~icons/mdi/clipboard-outline')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiCog: typeof import('~icons/mdi/cog')['default']
    IconMdiEmoticonSadOutline: typeof import('~icons/mdi/emoticon-sad-outline')['default']
    IconMdiHelp: typeof import('~icons/mdi/help')['default']
    IconMdiInformationOutline: typeof import('~icons/mdi/information-outline')['default']
    IconMdiLogin: typeof import('~icons/mdi/login')['default']
    IconMdiLogout: typeof import('~icons/mdi/logout')['default']
    IconMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IconMdiMenu: typeof import('~icons/mdi/menu')['default']
    IconMdiOpenInNew: typeof import('~icons/mdi/open-in-new')['default']
    IconMdiReloadAlert: typeof import('~icons/mdi/reload-alert')['default']
    IconMdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    IconMdiWeatherSunny: typeof import('~icons/mdi/weather-sunny')['default']
    IconMdiWindowClose: typeof import('~icons/mdi/window-close')['default']
    Licenses: typeof import('./src/components/Licenses.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/presence/Settings.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    UpdatePrompt: typeof import('./src/components/UpdatePrompt.vue')['default']
  }
}
